stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

.build:
  stage: build
  image: docker:27
  services:
    - docker:27-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:qoomlee:
  extends: .build
  rules:
    - changes:
        - services/qoomlee/**/*
        - infra/k8s/**/qoomlee/**/*
  script:
    - docker build --platform linux/amd64 -t "$CI_REGISTRY_IMAGE/qoomlee-service:$CI_COMMIT_SHA" -t "$CI_REGISTRY_IMAGE/qoomlee-service:latest" services/qoomlee
    - docker push "$CI_REGISTRY_IMAGE/qoomlee-service:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/qoomlee-service:latest"

build:payment:
  extends: .build
  rules:
    - changes:
        - services/payment/**/*
        - infra/k8s/**/payment/**/*
  script:
    - docker build --platform linux/amd64 -t "$CI_REGISTRY_IMAGE/payment-service:$CI_COMMIT_SHA" -t "$CI_REGISTRY_IMAGE/payment-service:latest" services/payment
    - docker push "$CI_REGISTRY_IMAGE/payment-service:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/payment-service:latest"

build:web:
  extends: .build
  rules:
    - changes:
        - app/web/**/*
        - infra/k8s/**/web/**/*
  script:
    - docker build --platform linux/amd64
        --build-arg NEXT_PUBLIC_QOOMLEE_API_URL=https://team-00-qoomlee-api.anuchito.com
        --build-arg NEXT_PUBLIC_PAYMENT_API_URL=https://team-00-payment-api.anuchito.com
        --build-arg NEXT_PUBLIC_ENABLE_TEST_SCENARIOS=true
        -t "$CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA"
        -t "$CI_REGISTRY_IMAGE/web:latest"
        app/web
    - docker push "$CI_REGISTRY_IMAGE/web:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE/web:latest"
