apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: qoomlee-hc
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        port: 8082
        requestPath: /health/ready
  targetRef:
    group: ""
    kind: Service
    name: qoomlee
