apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: qoomlee
  labels:
    team: team-00
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: qoomlee-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: Same
