apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
  labels:
    app: pgweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
        - name: pgweb
          image: sosedoff/pgweb:latest
          ports:
            - containerPort: 8081
          env:
            - name: PGWEB_HOST
              value: "postgres-qoomlee"
            - name: PGWEB_PORT
              value: "5432"
            - name: PGWEB_USER
              value: "qoomlee"
            - name: PGWEB_DATABASE
              value: "qoomlee"
            - name: PGWEB_SSLMODE
              value: "disable"
          command: ["/usr/bin/pgweb"]
          args:
            - "--bind=0.0.0.0"
            - "--listen=8081"
            - "--sessions"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
