apiVersion: v1
kind: ConfigMap
metadata:
  name: qoomlee-config
  namespace: qoomlee
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: qoomlee
  DB_USER: qoomlee

  FLIGHT_SERVICE_URL:  http://flight-service:8081
  BOOKING_SERVICE_URL: http://booking-service:8082
  PAYMENT_SERVICE_URL: http://payment-service:8084
