apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      team: team-00
    includeSelectors: false

resources:
  - qoomlee/deployment.yaml
  - qoomlee/service.yaml
  - payment/deployment.yaml
  - payment/service.yaml
  - web/deployment.yaml
  - web/service.yaml
  - gateway/gateway.yaml
  - gateway/httproutes.yaml

images:
  - name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/qoomlee-service
    newTag: latest
  - name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/payment-service
    newTag: latest
  - name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/web
    newTag: latest
