apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qoomlee-team-00-dev

labels:
  - pairs:
      env: dev
    includeSelectors: false

resources:
  - ../../base
  - namespace.yaml
  - configmaps.yaml

patches:
  - path: patch-httproutes.yaml

images:
  - name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/qoomlee-service
    newTag: dev
  - name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/payment-service
    newTag: dev
  - name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/web
    newTag: dev
