apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qoomlee-team-00-dev

labels:
- pairs:
    env: dev

resources:
- ../../base
- namespace.yaml
- configmaps.yaml

patches:
- path: patch-httproutes.yaml

images:
- name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/payment-service
  newTag: 4b9e36845823d0fef591c1c513dff4f3a67bf2b0
- name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/qoomlee-service
  newTag: 4b9e36845823d0fef591c1c513dff4f3a67bf2b0
- name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/web
  newTag: 4b9e36845823d0fef591c1c513dff4f3a67bf2b0
