apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qoomlee-team-00

labels:
- pairs:
    team: team-00

resources:
- ../../base
- namespace.yaml
- configmaps.yaml

patches:
- path: patch-httproutes.yaml

images:
- name: registry.gitlab.com/arise-by-infinitas/devrise-team-00-workshop/payment-service
  newTag: e312e9974639aef6b054728a2d5fc4f080bf4ea6
- name: registry.gitlab.com/arise-by-infinitas/devrise-team-00-workshop/qoomlee-service
  newTag: e312e9974639aef6b054728a2d5fc4f080bf4ea6
- name: registry.gitlab.com/arise-by-infinitas/devrise-team-00-workshop/web
  newTag: e312e9974639aef6b054728a2d5fc4f080bf4ea6
