---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qoomlee-api
spec:
  hostnames:
    - "api.dev.team-00.example.com"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: payment-api
spec:
  hostnames:
    - "payment.dev.team-00.example.com"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web
spec:
  hostnames:
    - "app.dev.team-00.example.com"
