apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qoomlee-team-00

labels:
- pairs:
    team: team-00

resources:
- ../../base
- namespace.yaml
- configmaps.yaml

patches:
- path: patch-httproutes.yaml

images:
- name: registry.gitlab.com/arise-by-infinitas/devrise-team-00-workshop/payment-service
  newTag: 6c0bf7e6c5e3f9eb3af0ad8639099271065e6367
- name: registry.gitlab.com/arise-by-infinitas/devrise-team-00-workshop/qoomlee-service
  newTag: 6a174d17c3e6c34d6b0b562176060ac530067261
- name: registry.gitlab.com/arise-by-infinitas/devrise-team-00-workshop/web
  newTag: 6c0bf7e6c5e3f9eb3af0ad8639099271065e6367
- name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/payment-service
  newTag: 792fa6e07b6f2f3d9180844a480fb04523817c8a
- name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/qoomlee-service
  newTag: 792fa6e07b6f2f3d9180844a480fb04523817c8a
- name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/web
  newTag: 792fa6e07b6f2f3d9180844a480fb04523817c8a
