apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qoomlee-team-00-prod

labels:
  - pairs:
      env: prod
    includeSelectors: false

resources:
  - ../../base
  - namespace.yaml
  - configmaps.yaml
  - hpa.yaml
  - pdb.yaml

patches:
  - path: patch-httproutes.yaml
  - path: patch-replicas.yaml

images:
  - name: ghcr.io/team-00/qoomlee-service
    newTag: "1.0.0"  # pin to a specific release tag in prod
  - name: ghcr.io/team-00/payment-service
    newTag: "1.0.0"
  - name: ghcr.io/team-00/web
    newTag: "1.0.0"
