apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qoomlee-team-00-prod

labels:
  - pairs:
      env: prod
    includeSelectors: false

resources:
  - ../../base
  - namespace.yaml
  - configmaps.yaml
  - hpa.yaml
  - pdb.yaml

patches:
  - path: patch-httproutes.yaml
  - path: patch-replicas.yaml

images:
  - name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/qoomlee-service
    newTag: latest
  - name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/payment-service
    newTag: latest
  - name: registry.gitlab.com/arise-by-infinitas/devrise-workshop/web
    newTag: latest
